version: '3.8'

services:
  exam:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - .env.dev
    depends_on:
        - exam-db
  exam-db:
    image: postgres:14-alpine
    volumes:
      - exam-db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=exam
      - POSTGRES_PASSWORD=exam
      - POSTGRES_DB=exam_dev
volumes:
    exam-db-data:
